// <auto-generated />
using System;
using FinalCarDealershipApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalCarDealershipApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240412132531_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalCarDealershipApplication.Models.Admins", b =>
                {
                    b.Property<string>("adminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("adminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FinalCarDealershipApplication.Models.Cars", b =>
                {
                    b.Property<string>("carID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("carID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("FinalCarDealershipApplication.Models.Customers", b =>
                {
                    b.Property<string>("customerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("customerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FinalCarDealershipApplication.Models.Sales", b =>
                {
                    b.Property<string>("saleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CarscarID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerscustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("saleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("saleId");

                    b.HasIndex("CarscarID");

                    b.HasIndex("CustomerscustomerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("FinalCarDealershipApplication.Models.Transactions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinalCarDealershipApplication.Models.User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalCarDealershipApplication.Models.Sales", b =>
                {
                    b.HasOne("FinalCarDealershipApplication.Models.Cars", "Cars")
                        .WithMany()
                        .HasForeignKey("CarscarID");

                    b.HasOne("FinalCarDealershipApplication.Models.Customers", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomerscustomerId");

                    b.Navigation("Cars");

                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
